---
name: Build and Test

on:
  push:
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build dockerimage
        run: docker build -t newgit .
      - name: Run tests
        run: docker run newgit test 
        
