---
name: SonarCloud Quality Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3

      - name: SonarScanner for .NET 7 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.2.6
        with:
          sonarProjectKey: duckth_bdsa-project-newgit
          sonarProjectName: bdsa-project-newgit
          sonarOrganization: duckth
          dotnetPreBuildCmd: dotnet user-secrets set --project NEWgIT.Core PAT:NEWgIT ${{ secrets.GITHUB_TOKEN }}
          dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
