---
name: SonarCloud Quality Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarScanner for .NET 6 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.1.3
        with:
          sonarProjectKey: duckth_bdsa-project-newgit
          sonarProjectName: bdsa-project-newgit
          sonarOrganization: duckth

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
